name: Test & Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7' ]
        experimental: [ false ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: curl https://deepsource.io/cli | sh
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: bundle exec rubocop --auto-correct --fail-level A
      - uses: bissy-io/autolint@v0.0.3
        if: ${{ github.event_name == 'pull_request' && always() }}
      - run: bundle exec rspec --format progress
      - run: ./bin/deepsource report --analyzer test-coverage --key ruby --value-file ./coverage/.resultset.json
